name: distinct_value_connectable_observable
description: A starting point for Dart libraries or applications.
version: 1.0.0
homepage: https://www.example.com
author: Petrus Nguyễn Thái Học <hoc081098@gmail.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  rxdart: ^0.20.0

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
  mockito: ^3.0.0
